name: Build python

on: [push, pull_request]

jobs:
        build:
                name: compile
                runs-on: ubuntu-latest
                steps:
                      - uses: actions/checkout@v2
                      - run: ls ${{ github.workspace }}
                      - run: python3 -m py_compile ${{github.workspace}}/echo_bot.py

