name: Publish docker image

on:
        release:
                types: [published]

jobs:
        publish:
                runs-on: ubuntu-latest
                steps:
                        - name: Check out the repo
                          uses: actions/checkout@v2
                        
                        - name: Wait for build to succeed
                          uses: lewagon/wait-on-check-action@v1.0.0
                          with:
                                  ref: ${{ github.ref }}
                                  check-name: 'compile'
                                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                                  wait-interval: 10

                        - name: Log in to Docker Hub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

                        - name: Build and push
                          id: docker_build
                          uses: docker/build-push-action@v2
                          with:
                                  push: true
                                  tags: ${{ secrets.DOCKER_USERNAME }}/jason_statham_bot:latest

